language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
install:
  - 'make install'
before_script:
  - 'echo "xdebug.mode = coverage" >>~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini'
script:
  - 'make test lint'
