name: Drip PHP API Client Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: make install
      - run: make test lint
    strategy:
      matrix:
        php:
          - '7.4'
          - '8.0'
          - '8.1'
